### ISSUE TITLE
你好，我试了一下你讲的方法，发现现在第五批次口罩，用charles好像抓不到需要的信息了，大神能不能再研究一下

### ISSUE THREAD

**Issue by ntwlwjl** [modianor/MaskSnatchingScript#1]

**Comment by modianor** [comment]
看到你这个issue，我首先打开电脑测试了下，发现可以抓到session_key
![image](https://user-images.githubusercontent.com/24886976/75626290-4de81700-5c01-11ea-975e-183ac9f75aa5.png)
可能还是你的Charles的配置不对 我这里推荐按照这个blog重新配置一下Charles https://blog.csdn.net/liqing0013/article/details/83010531
