### ISSUE TITLE
现在的第六批口罩还能用吗？

### ISSUE THREAD

**Issue by ntwlwjl** [modianor/MaskSnatchingScript#2]
大神，我用了你的源码，选了个离家较近的药店，可是一到时间程序就卡了，过一会儿就没库存了，什么原因啊？请指教

**Comment by modianor** [comment]
可以 我遇到过这个问题 你电脑的网络状况很重要 如果是WiFi的话最后能插网线。提前运行，发现卡主可以立即终止再次运行。还有就是你自己知道了商品id和药店id，可以手动指定，不一定需要每次动态获取，可以加快速度。
